### PR TITLE
Theme select + type fixes

### PR DESCRIPTION
**Pull request by Juuddi**
- Added theme select modal + cookie handling to save user's theme choice
- Additional type fixes and simplifications

### CODE REVIEW

**Comment by Juuddi** [comment]
WIP branch for new features prior to adding smart contract functionality

**Review by DenisIvanov26 — APPROVED** [review]

**Comment by Juuddi** [comment]
- Reworked main modal for simplicity
- Popped out account frame into it's own modal
- Added easy bet selection buttons
- Fixed gameTable coloring issue
- Refactored start menu on taskbar

**Comment by Juuddi** [comment]
- Removed all state management from smart contract for economics and prep for later database integration
- Removed rendering of flip stats table as it's no longer relevant (saved code for later use though)
- Moved contract data pull logic to `GameComponents.tsx`
- Added stats/details to main modal that includes total flips and current contract balance
- Removed Flip details from `TaskBar.tsx` and `DesktopIcons.tsx`, also removed reference in globally defined interfaces
- Reworked `useContract.ts` hook to reflect contract changes
- Added helper function that maps explorer URLs to address by shard
- Minor styling and spacing fixes for main modal

**Comment by Juuddi** [comment]
Flip flow is preliminarily mocked in this PR. Merging and moving to next large scale task.

**Pull request merged**
